dist: xenial
sudo: false

language: generic

jdk:
  - oraclejdk8

notifications:
  email: false

services:
  - redis-server
  - docker

addons:
  postgresql: "9.5"
  apt:
    packages:
      - net-tools
      - libpcre3-dev
      - build-essential

env:
  global:
    - LUAROCKS=3.0.4
    - OPENSSL=1.1.1a
    - OPENRESTY_BASE=1.13.6.2
    - OPENRESTY_LATEST=1.13.6.2
    - OPENRESTY=$OPENRESTY_BASE
    - CASSANDRA=3.9

    - DOWNLOAD_CACHE=$HOME/download-cache
    - INSTALL_CACHE=$HOME/install-cache

    - KONG_TEST_PG_DATABASE=travis
    - KONG_TEST_PG_USER=postgres
    - KONG_TEST_CASSANDRA_KEYSPACE=kong_tests
    - KONG_TEST_DB_UPDATE_PROPAGATION=1

    - PLUGIN_NAME=corax
    - KONG_PLUGINS=bundled,$PLUGIN_NAME

before_install:
  - git clone https://github.com/Kong/kong.git kong-ce
  - source kong-ce/.ci/setup_env.sh

install:
  - luarocks make
  - export LUA_PATH="`pwd`/?.lua;`pwd`/?/init.lua;$LUA_PATH"
  - cd kong-ce && make dev

script:
  - bin/busted -o gtest -v --exclude-tags=cassandra ../spec

cache:
  apt: true
  pip: true
  directories:
    - $DOWNLOAD_CACHE
    - $INSTALL_CACHE
    - $HOME/.ccm/repository
